const PDFDocument = require('pdfkit');

/**
 * Case Strategy PDF Generator
 * Generates professional Legal Strategy Memorandum
 */

/**
 * Generate PDF Strategy
 * @param {Object} data - { session, user }
 * @returns {Promise<Buffer>} - PDF Buffer
 */
async function generateStrategyPDF(data) {
    return new Promise((resolve, reject) => {
        try {
            const { session, user } = data;
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 72, bottom: 72, left: 72, right: 72 } // 1 inch margins
            });

            const chunks = [];
            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', (err) => reject(err));

            // --- HEADER ---
            doc.fontSize(20).font('Helvetica-Bold').text('STRATEGIC LEGAL MEMORANDUM', { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica').text('CONFIDENTIAL - FOR ADVOCATE USE ONLY', { align: 'center', color: '#ff0000' });
            doc.moveDown(2);

            // --- METADATA ---
            doc.fontSize(12).font('Helvetica-Bold').text('CASE REFERENCE: ', { continued: true }).font('Helvetica').text(session._id.toString());
            doc.fontSize(12).font('Helvetica-Bold').text('CLIENT POSITION: ', { continued: true }).font('Helvetica').text(session.caseDetails.clientPosition.toUpperCase());
            doc.fontSize(12).font('Helvetica-Bold').text('FORUM: ', { continued: true }).font('Helvetica').text(session.caseDetails.courtLevel.toUpperCase());
            doc.fontSize(12).font('Helvetica-Bold').text('DATE: ', { continued: true }).font('Helvetica').text(new Date().toLocaleDateString('en-PK'));
            doc.moveDown(2);

            // --- HORIZONTAL LINE ---
            doc.moveTo(72, doc.y).lineTo(523, doc.y).strokeColor('#cccccc').stroke().moveDown(1.5);

            // --- CONTENT (Strategy Parsing) ---
            // The strategy is markdown. We'll do simple parsing for headers.
            const lines = session.strategy.split('\n');
            
            lines.forEach(line => {
                if (line.startsWith('# ')) {
                    doc.moveDown(1);
                    doc.fontSize(16).font('Helvetica-Bold').fillColor('#000000').text(line.replace('# ', '').trim());
                    doc.moveDown(0.5);
                } else if (line.startsWith('## ')) {
                    doc.moveDown(0.8);
                    doc.fontSize(14).font('Helvetica-Bold').fillColor('#2c3e50').text(line.replace('## ', '').trim());
                    doc.moveDown(0.5);
                } else if (line.startsWith('### ')) {
                    doc.moveDown(0.5);
                    doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e').text(line.replace('### ', '').trim());
                    doc.moveDown(0.3);
                } else if (line.trim().startsWith('* ') || line.trim().startsWith('- ')) {
                    doc.fontSize(11).font('Helvetica').fillColor('#333333').text(`• ${line.trim().substring(2)}`, { indent: 20, align: 'justify' });
                    doc.moveDown(0.2);
                } else if (line.trim().length > 0) {
                    // Check for bold text **like this**
                    const text = line.trim();
                    doc.fontSize(11).font('Helvetica').fillColor('#333333').text(text, { align: 'justify' });
                    doc.moveDown(0.5);
                }
            });

            // --- FOOTER ---
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(8).fillColor('#999999').text(
                    `Generated by Legalyze AI - Page ${i + 1} of ${pages.count}`,
                    72, 
                    770, 
                    { align: 'center', width: 451 }
                );
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

module.exports = {
    generateStrategyPDF
};
